#!/bin/bash
BASEPATH=~/Dev/aoc-2022
DAY=$1
if [ -z "$DAY" ]; then
  DAY=$(date +%d | sed 's/^0*//')
fi
URL=https://adventofcode.com/2022/day/$DAY/input
DAY_PATH=$(printf "%02d" $DAY)
PROJECT=day-$DAY_PATH
echo $PROJECT

if [ -d "./$PROJECT" ]; then
  echo "Project '$PROJECT' already exists, exiting..."
  exit 0;
fi

cargo init $PROJECT
cp template/* $PROJECT/src/
curl $URL -b $(cat aoc_cookie) -o $PROJECT/input
echo "done."
cd $PROJECT
